package com.nabil.form;

import com.nabil.database.KonekDatabase;
import com.nabil.images.BackgroundImage;
import com.nabil.utilities.Utilities;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Nabil Fawwaz
 */
public class Laporan extends javax.swing.JFrame {

    Statement st;
    ResultSet rs;
    KonekDatabase koneksi;
    PreparedStatement pst;
    Utilities utilities;

    /**
     * Creates new form Transaction
     */
    public Laporan() {
        initComponents();
        koneksi = new KonekDatabase();
        utilities = new Utilities();
        setLocationRelativeTo(null);
        table1();
        table2();
        table3();
        fpinjam_semua_waktu.setText(Integer.toString(getSumLoan()));
        FTSimpanan_Semua_Waktu.setText(Integer.toString(getSumSave()));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/nabil/images/logo.png")));
        Panel_Utama.requestFocusInWindow();
        nomor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Utama = new BackgroundImage(file);
        Panel_Semua_Waktu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        LTSimpanan_semua_waktu = new javax.swing.JLabel();
        fpinjam_semua_waktu = new javax.swing.JTextField();
        LTPinjaman_Semua_Waktu = new javax.swing.JLabel();
        FTSimpanan_Semua_Waktu = new javax.swing.JTextField();
        Panel_Bulan_Ini = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        FTPinjaman_Bulan_Ini = new javax.swing.JTextField();
        LTPinjaman_Bulan_Ini = new javax.swing.JLabel();
        LTSimpanan_Bulan_Ini = new javax.swing.JLabel();
        FTSimpan_Bulan_Ini = new javax.swing.JTextField();
        Panel_Rekapitulasi = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        tsimpan = new javax.swing.JButton();
        thitung = new javax.swing.JButton();
        tbersih = new javax.swing.JButton();
        tambildata = new javax.swing.JButton();
        thapus = new javax.swing.JButton();
        nomor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan");
        setResizable(false);

        Panel_Utama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));

        Panel_Semua_Waktu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Semua Waktu")));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Member ID", "Date", "Member's Loan", "Member's Save"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        LTSimpanan_semua_waktu.setText("Total Simpanan Semua Waktu");

        fpinjam_semua_waktu.setEditable(false);

        LTPinjaman_Semua_Waktu.setText("Total Pinjaman Semua Waktu");

        FTSimpanan_Semua_Waktu.setEditable(false);

        javax.swing.GroupLayout Panel_Semua_WaktuLayout = new javax.swing.GroupLayout(Panel_Semua_Waktu);
        Panel_Semua_Waktu.setLayout(Panel_Semua_WaktuLayout);
        Panel_Semua_WaktuLayout.setHorizontalGroup(
            Panel_Semua_WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Semua_WaktuLayout.createSequentialGroup()
                .addGroup(Panel_Semua_WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Semua_WaktuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LTPinjaman_Semua_Waktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fpinjam_semua_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LTSimpanan_semua_waktu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FTSimpanan_Semua_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        Panel_Semua_WaktuLayout.setVerticalGroup(
            Panel_Semua_WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Semua_WaktuLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(Panel_Semua_WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpinjam_semua_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTPinjaman_Semua_Waktu)
                    .addComponent(LTSimpanan_semua_waktu)
                    .addComponent(FTSimpanan_Semua_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Panel_Bulan_Ini.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Bulan Ini")));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Member ID", "Date", "Member's Loan", "Member's Save"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table2);
        if (table2.getColumnModel().getColumnCount() > 0) {
            table2.getColumnModel().getColumn(0).setResizable(false);
            table2.getColumnModel().getColumn(1).setResizable(false);
        }

        FTPinjaman_Bulan_Ini.setEditable(false);

        LTPinjaman_Bulan_Ini.setText("Total Pinjaman Bulan Ini");

        LTSimpanan_Bulan_Ini.setText("Total Simpanan Bulan Ini");

        FTSimpan_Bulan_Ini.setEditable(false);

        javax.swing.GroupLayout Panel_Bulan_IniLayout = new javax.swing.GroupLayout(Panel_Bulan_Ini);
        Panel_Bulan_Ini.setLayout(Panel_Bulan_IniLayout);
        Panel_Bulan_IniLayout.setHorizontalGroup(
            Panel_Bulan_IniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Bulan_IniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LTPinjaman_Bulan_Ini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FTPinjaman_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTSimpanan_Bulan_Ini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FTSimpan_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
        );
        Panel_Bulan_IniLayout.setVerticalGroup(
            Panel_Bulan_IniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Bulan_IniLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Bulan_IniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTPinjaman_Bulan_Ini)
                    .addComponent(FTPinjaman_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTSimpanan_Bulan_Ini)
                    .addComponent(FTSimpan_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Panel_Rekapitulasi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Rekapitulasi")));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Total Loan All Time", "Total Save This Time", "Total Loan This Month", "Total Save This Month"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table3MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table3MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(table3);

        javax.swing.GroupLayout Panel_RekapitulasiLayout = new javax.swing.GroupLayout(Panel_Rekapitulasi);
        Panel_Rekapitulasi.setLayout(Panel_RekapitulasiLayout);
        Panel_RekapitulasiLayout.setHorizontalGroup(
            Panel_RekapitulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        Panel_RekapitulasiLayout.setVerticalGroup(
            Panel_RekapitulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );

        tsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nabil/images/save.png"))); // NOI18N
        tsimpan.setText("Simpan  ");
        tsimpan.setEnabled(false);
        tsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tsimpanMouseEntered(evt);
            }
        });
        tsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsimpanActionPerformed(evt);
            }
        });

        thitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nabil/images/calculate.png"))); // NOI18N
        thitung.setText("Hitung     ");
        thitung.setEnabled(false);
        thitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thitungMouseEntered(evt);
            }
        });
        thitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thitungActionPerformed(evt);
            }
        });

        tbersih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nabil/images/clear.png"))); // NOI18N
        tbersih.setText("Bersih     ");
        tbersih.setEnabled(false);
        tbersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbersihMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbersihMouseEntered(evt);
            }
        });
        tbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbersihActionPerformed(evt);
            }
        });

        tambildata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nabil/images/getdata.png"))); // NOI18N
        tambildata.setText("Ambil Data");
        tambildata.setEnabled(false);
        tambildata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambildataMouseEntered(evt);
            }
        });
        tambildata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambildataActionPerformed(evt);
            }
        });

        thapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nabil/images/delete.png"))); // NOI18N
        thapus.setText("Hapus     ");
        thapus.setEnabled(false);
        thapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thapusMouseEntered(evt);
            }
        });
        thapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thapusActionPerformed(evt);
            }
        });

        nomor.setText("nomor");

        javax.swing.GroupLayout Panel_UtamaLayout = new javax.swing.GroupLayout(Panel_Utama);
        Panel_Utama.setLayout(Panel_UtamaLayout);
        Panel_UtamaLayout.setHorizontalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Semua_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_UtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambildata)
                .addGap(18, 18, 18)
                .addComponent(tbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(thitung, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(Panel_Rekapitulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_UtamaLayout.setVerticalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel_Semua_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Bulan_Ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thitung)
                    .addComponent(tbersih)
                    .addComponent(tambildata)
                    .addComponent(tsimpan)
                    .addComponent(thapus)
                    .addComponent(nomor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Rekapitulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String file = "/com/nabil/images/bgt.jpg";

    public int getSumLoan() { //Koding menjumlahkan dari row yang dipilih ke jTextField
        int rowsCount = table1.getRowCount();
        int sum = 0;
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Integer.parseInt(table1.getValueAt(i, 2).toString());
        }
        return sum;
    }

    public int getSumSave() {
        int rowsCount = table1.getRowCount();
        int sum = 0;
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Integer.parseInt(table1.getValueAt(i, 3).toString());
        }
        return sum;
    }

    public int getSumLoan2() {
        int rowsCount = table2.getRowCount();
        int sum = 0;
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Integer.parseInt(table2.getValueAt(i, 2).toString());
        }
        return sum;
    }

    public int getSumSave2() {
        int rowsCount = table2.getRowCount();
        int sum = 0;
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Integer.parseInt(table2.getValueAt(i, 3).toString());
        }
        return sum;
    }

    private void table1() {//Menampilkan table ksp dari database di table1
        DefaultTableModel data = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table1.getRowCount();
        table1.setModel(data);
        data.addColumn("ID");
        data.addColumn("Tanggal");
        data.addColumn("Pinjaman Anggota");
        data.addColumn("Simpanan Anggota");

        TableColumn column;
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = table1.getColumnModel().getColumn(0);
        column.setPreferredWidth(54);
        column = table1.getColumnModel().getColumn(1);
        column.setPreferredWidth(80);
        column = table1.getColumnModel().getColumn(2);
        column.setPreferredWidth(192);
        column = table1.getColumnModel().getColumn(3);
        column.setPreferredWidth(191);

        String sql = "SELECT * FROM ksp"; //Menampilkan semua data ksp di table1
        try {
            st = koneksi.con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                String kolom1 = rs.getString(2); //Mendapatkan semua data
                String kolom2 = rs.getString(8);
                String kolom3 = rs.getString(13);
                String kolom4 = rs.getString(11);
                String kolom[] = {kolom1, kolom2, kolom3, kolom4};
                data.addRow(kolom);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak terhubung dengan database\n" + e,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void table2() {
        DefaultTableModel data = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table2.getRowCount();
        table2.setModel(data);
        data.addColumn("ID");
        data.addColumn("Tanggal");
        data.addColumn("Pinjaman Anggota");
        data.addColumn("Simpanan Anggota");

        TableColumn column;
        table2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = table2.getColumnModel().getColumn(0);
        column.setPreferredWidth(54);
        column = table2.getColumnModel().getColumn(1);
        column.setPreferredWidth(80);
        column = table2.getColumnModel().getColumn(2);
        column.setPreferredWidth(162);
        column = table2.getColumnModel().getColumn(3);
        column.setPreferredWidth(163);
    }

    private void table3() {
        DefaultTableModel data = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table3.getRowCount();
        table3.setModel(data);
        data.addColumn("No");
        data.addColumn("Tanggal Laporan");
        data.addColumn("Total Pinjaman Semua Waktu");
        data.addColumn("Total Simpanan Semua Waktu");
        data.addColumn("Total Pinjaman Bulan Ini");
        data.addColumn("Total Simpanan Bulan Ini");

        TableColumn column;
        table3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = table3.getColumnModel().getColumn(0);
        column.setPreferredWidth(37);
        column = table3.getColumnModel().getColumn(1);
        column.setPreferredWidth(121);
        column = table3.getColumnModel().getColumn(2);
        column.setPreferredWidth(188);
        column = table3.getColumnModel().getColumn(3);
        column.setPreferredWidth(193);
        column = table3.getColumnModel().getColumn(4);
        column.setPreferredWidth(161);
        column = table3.getColumnModel().getColumn(5);
        column.setPreferredWidth(161);

        String sql = "SELECT * FROM kspt"; ////Menampilkan table kspt dari database di table1
        try {
            st = koneksi.con.createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                String kolom0 = rs.getString(1);
                String kolom1 = rs.getString(2);
                String kolom2 = rs.getString(3);
                String kolom3 = rs.getString(4);
                String kolom4 = rs.getString(5);
                String kolom5 = rs.getString(6);
                String kolom[] = {kolom0, kolom1, kolom2, kolom3, kolom4, kolom5};
                data.addRow(kolom);
            }
        } catch (SQLException e) {
            System.out.print("ERROR: " + e);
        }
    }

    private void tambildataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambildataActionPerformed
        utilities.clickGo();
        TableModel model1 = table1.getModel();
        int[] indexs = table1.getSelectedRows();
        Object[] row = new Object[4];
        DefaultTableModel model2 = (DefaultTableModel) table2.getModel();
        for (int i = 0; i < indexs.length; i++) {
            row[0] = model1.getValueAt(indexs[i], 0);
            row[1] = model1.getValueAt(indexs[i], 1);
            row[2] = model1.getValueAt(indexs[i], 2);
            row[3] = model1.getValueAt(indexs[i], 3);
            model2.addRow(row);
        }
        thitung.setEnabled(true);
        tbersih.setEnabled(true);
    }//GEN-LAST:event_tambildataActionPerformed

    private void tbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbersihActionPerformed
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        model.setRowCount(0);
        thitung.setEnabled(false);
        tbersih.setEnabled(false);
        tambildata.setEnabled(false);
        FTPinjaman_Bulan_Ini.setText("");
        FTSimpan_Bulan_Ini.setText("");
        nomor.setText("");
        Panel_Utama.requestFocusInWindow();
        table1.getSelectionModel().clearSelection(); //Tombol Bersih
        tsimpan.setEnabled(false);
        thapus.setEnabled(false);
    }//GEN-LAST:event_tbersihActionPerformed

    private void thitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thitungActionPerformed
        utilities.clickGo();
        FTPinjaman_Bulan_Ini.setText("0");
        FTSimpan_Bulan_Ini.setText("0");
        FTPinjaman_Bulan_Ini.setText(Integer.toString(getSumLoan2()));
        FTSimpan_Bulan_Ini.setText(Integer.toString(getSumSave2()));
        tsimpan.setEnabled(true);
    }//GEN-LAST:event_thitungActionPerformed

    Date currentDate = new Date();
    String currentdate = new SimpleDateFormat("yyyy-MM-dd").format(currentDate);
    private void tsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsimpanActionPerformed
        utilities.clickGo();
        int ok = JOptionPane.showConfirmDialog(null, "Apa kamu yakin ingin menyimpan data ini?",
                "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        try { //Tombol Simpan
            if (ok == JOptionPane.YES_OPTION) {
                utilities.clickGo();
                st = koneksi.con.createStatement();
                String sql = "INSERT INTO kspt(Tgl_Laporan,"
                        + "Jml_Pnj_SW,"
                        + "Jml_Smp_SW,"
                        + "Jml_Pnj_BI,"
                        + "Jml_Smp_Bi)"
                        + "VALUES ('" + currentdate
                        + "','" + fpinjam_semua_waktu.getText()
                        + "','" + FTSimpanan_Semua_Waktu.getText()
                        + "','" + FTPinjaman_Bulan_Ini.getText()
                        + "','" + FTSimpan_Bulan_Ini.getText() + "')";
                String sql2 = "ALTER TABLE kspt DROP No";
                String sql3 = "ALTER TABLE kspt ADD  No INT( 11 ) NOT NULL AUTO_INCREMENT FIRST ,ADD PRIMARY KEY (No)";
                st.executeUpdate(sql);
                st.executeUpdate(sql2);
                st.executeUpdate(sql3);
                table3();
                utilities.clickSuccess();
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan",
                        "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                tbersihActionPerformed(evt);
            } else if (ok == JOptionPane.NO_OPTION) {
                utilities.clickCancel();
                tbersihActionPerformed(evt);
            }
        } catch (SQLException e) {
            utilities.clickError();
            JOptionPane.showMessageDialog(null, "Data tidak berhasil tersimpan\n" + e);
            tbersihActionPerformed(evt);
        }
    }//GEN-LAST:event_tsimpanActionPerformed

    private void thapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thapusActionPerformed
        utilities.clickGo();
        int ok = JOptionPane.showConfirmDialog(null, "Apa kamu yakin ingin menghapus data ini?",
                "CONFIRMATION", JOptionPane.YES_NO_OPTION);
        try { //Delete Record
            if (ok == JOptionPane.YES_OPTION) {
                utilities.clickGo();
                String sql = "delete from kspt where No=?";
                pst = koneksi.con.prepareStatement(sql);
                pst.setString(1, nomor.getText());
                pst.execute();
                String sql2 = "ALTER TABLE kspt DROP No";
                String sql3 = "ALTER TABLE kspt ADD  No INT( 11 ) NOT NULL AUTO_INCREMENT FIRST ,ADD PRIMARY KEY (No)";
                st.executeUpdate(sql2);
                st.executeUpdate(sql3);
                table3();
                tbersihActionPerformed(evt);
                utilities.clickSuccess();
                JOptionPane.showMessageDialog(null, "Data berhasil terhapus");
            } else if (ok == JOptionPane.NO_OPTION) {
                utilities.clickCancel();
                tbersihActionPerformed(evt);
            }
        } catch (SQLException e) {
            utilities.clickFailure();
            JOptionPane.showMessageDialog(null, "Data tidak terhapus\n" + e,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_thapusActionPerformed

    private void table3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseReleased
        utilities.clickGo();
        int a = table3.getSelectedRow();
        if (a >= 0) {
            table3.setRowSelectionInterval(a, a);
            thapus.setEnabled(true);
            int baris = table3.getSelectedRow();
            TableModel model = table3.getModel();
            nomor.setText(model.getValueAt(baris, 0).toString());
            FTSimpanan_Semua_Waktu.setText(model.getValueAt(baris, 2).toString());
            fpinjam_semua_waktu.setText(model.getValueAt(baris, 3).toString());
            FTSimpan_Bulan_Ini.setText(model.getValueAt(baris, 4).toString());
            FTPinjaman_Bulan_Ini.setText(model.getValueAt(baris, 5).toString());
        } else {
            thapus.setEnabled(false);
            FTPinjaman_Bulan_Ini.setText("");
            FTSimpan_Bulan_Ini.setText("");
        }
    }//GEN-LAST:event_table3MouseReleased

    private void table1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MousePressed
        utilities.clickGo();
        int a = table1.getSelectedRow();
        if (a >= 0) {
            tambildata.setEnabled(true);
        } else {
            tambildata.setEnabled(false);
        }
    }//GEN-LAST:event_table1MousePressed

    private void table1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseEntered
        utilities.clickHover();
        table1.requestFocusInWindow();
    }//GEN-LAST:event_table1MouseEntered

    private void table2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MousePressed
        utilities.clickGo();

    }//GEN-LAST:event_table2MousePressed

    private void table2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseEntered
        utilities.clickHover();
        table2.requestFocusInWindow();
    }//GEN-LAST:event_table2MouseEntered

    private void table3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseEntered
        utilities.clickHover();
        table3.requestFocusInWindow();
    }//GEN-LAST:event_table3MouseEntered

    private void tbersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbersihMouseClicked
        utilities.clickGo();
    }//GEN-LAST:event_tbersihMouseClicked

    private void tbersihMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbersihMouseEntered
        if (tbersih.isEnabled()) {
            utilities.clickHover();
        }
    }//GEN-LAST:event_tbersihMouseEntered

    private void thitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thitungMouseEntered
        if (thitung.isEnabled()) {
            utilities.clickHover();
        }
    }//GEN-LAST:event_thitungMouseEntered

    private void tsimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsimpanMouseEntered
        if (tsimpan.isEnabled()) {
            utilities.clickHover();
        }
    }//GEN-LAST:event_tsimpanMouseEntered

    private void thapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thapusMouseEntered
        if (thapus.isEnabled()) {
            utilities.clickHover();
        }
    }//GEN-LAST:event_thapusMouseEntered

    private void tambildataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambildataMouseEntered
        if (tambildata.isEnabled()) {
            utilities.clickHover();
        }
    }//GEN-LAST:event_tambildataMouseEntered

    /**
     * @param args the command line arguments
     * @throws java.text.ParseException
     */
    public static void main(String args[]) throws ParseException {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.print("ERROR: " + ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Laporan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FTPinjaman_Bulan_Ini;
    private javax.swing.JTextField FTSimpan_Bulan_Ini;
    private javax.swing.JTextField FTSimpanan_Semua_Waktu;
    private javax.swing.JLabel LTPinjaman_Bulan_Ini;
    private javax.swing.JLabel LTPinjaman_Semua_Waktu;
    private javax.swing.JLabel LTSimpanan_Bulan_Ini;
    private javax.swing.JLabel LTSimpanan_semua_waktu;
    private javax.swing.JPanel Panel_Bulan_Ini;
    private javax.swing.JPanel Panel_Rekapitulasi;
    private javax.swing.JPanel Panel_Semua_Waktu;
    private javax.swing.JPanel Panel_Utama;
    private javax.swing.JTextField fpinjam_semua_waktu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nomor;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JButton tambildata;
    private javax.swing.JButton tbersih;
    private javax.swing.JButton thapus;
    private javax.swing.JButton thitung;
    private javax.swing.JButton tsimpan;
    // End of variables declaration//GEN-END:variables
}
